### ISSUE TITLE
Builds git HEAD

### ISSUE THREAD

**Issue by Lartza** [sanduhrs/arch-aur-php-uploadprogress#1]
The package is incorrectly a duplicate of php-uploadprogress-git that pins the pkgver to 1.0.3.1 but builds git HEAD

**Comment by sanduhrs** [comment]
This has been fixed in https://github.com/sanduhrs/arch-aur-php-uploadprogress/commit/5acf9c2919c082a5454b2a8d330b78b1e4aaf4a4#diff-da6e50bd048b01fce3a730750d3f6fc41a3ddbe8c2e8ac6e4f7d4ef09fc1e124R14
Thanks for reporting!
